// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAybtUIEKLhMCn1ouUCKjy2gw_GliKeFoI',
    appId: '1:1033810261503:web:edc5bba01b1501549fe3ca',
    messagingSenderId: '1033810261503',
    projectId: 'mindmatch-ba671',
    authDomain: 'mindmatch-ba671.firebaseapp.com',
    storageBucket: 'mindmatch-ba671.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAybtUIEKLhMCn1ouUCKjy2gw_GliKeFoI',
    appId: '1:1033810261503:android:edc5bba01b1501549fe3ca',
    messagingSenderId: '1033810261503',
    projectId: 'mindmatch-ba671',
    storageBucket: 'mindmatch-ba671.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAybtUIEKLhMCn1ouUCKjy2gw_GliKeFoI',
    appId: '1:1033810261503:ios:edc5bba01b1501549fe3ca',
    messagingSenderId: '1033810261503',
    projectId: 'mindmatch-ba671',
    storageBucket: 'mindmatch-ba671.firebasestorage.app',
    iosBundleId: 'com.company.mindmatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAybtUIEKLhMCn1ouUCKjy2gw_GliKeFoI',
    appId: '1:1033810261503:ios:edc5bba01b1501549fe3ca',
    messagingSenderId: '1033810261503',
    projectId: 'mindmatch-ba671',
    storageBucket: 'mindmatch-ba671.firebasestorage.app',
    iosBundleId: 'com.company.mindmatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAybtUIEKLhMCn1ouUCKjy2gw_GliKeFoI',
    appId: '1:1033810261503:web:edc5bba01b1501549fe3ca',
    messagingSenderId: '1033810261503',
    projectId: 'mindmatch-ba671',
    authDomain: 'mindmatch-ba671.firebaseapp.com',
    storageBucket: 'mindmatch-ba671.firebasestorage.app',
  );
}
